### ISSUE TITLE
RuntimeError: cuda runtime error (801) : operation not supported at C:\w\1\s\windows\pytorch\torch/csrc/generic/StorageSharing.cpp:245

### ISSUE THREAD

**Issue by ShowTimeJMJ** [fastai/fastbook#85]
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-01238be27a86> in <module>
      9 
     10 learn = cnn_learner(dls, resnet34, metrics=error_rate)
---> 11 learn.fine_tune(1)

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fastai2\callback\schedule.py in fine_tune(self, epochs, base_lr, freeze_epochs, lr_mult, pct_start, div, **kwargs)
    155     "Fine tune with `freeze` for `freeze_epochs` then with `unfreeze` from `epochs` using discriminative LR"
    156     self.freeze()
--> 157     self.fit_one_cycle(freeze_epochs, slice(base_lr), pct_start=0.99, **kwargs)
    158     base_lr /= 2
    159     self.unfreeze()

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fastai2\callback\schedule.py in fit_one_cycle(self, n_epoch, lr_max, div, div_final, pct_start, wd, moms, cbs, reset_opt)
    110     scheds = {'lr': combined_cos(pct_start, lr_max/div, lr_max, lr_max/div_final),
    111               'mom': combined_cos(pct_start, *(self.moms if moms is None else moms))}
--> 112     self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
    113 
    114 # Cell

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fastai2\learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    190                     try:
    191                         self.epoch=epoch;          self('begin_epoch')
--> 192                         self._do_epoch_train()
    193                         self._do_epoch_validate()
    194                     except CancelEpochException:   self('after_cancel_epoch')

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fastai2\learner.py in _do_epoch_train(self)
    163         try:
    164             self.dl = self.dls.train;                        self('begin_train')
--> 165             self.all_batches()
    166         except CancelTrainException:                         self('after_cancel_train')
    167         finally:                                             self('after_train')

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fastai2\learner.py in all_batches(self)
    141     def all_batches(self):
    142         self.n_iter = len(self.dl)
--> 143         for o in enumerate(self.dl): self.one_batch(*o)
    144 
    145     def one_batch(self, i, b):

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\fastai2\data\load.py in __iter__(self)
     95         self.randomize()
     96         self.before_iter()
---> 97         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
     98             if self.device is not None: b = to_device(b, self.device)
     99             yield self.after_batch(b)

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    717             #     before it starts, and __del__ tries to join but will get:
    718             #     AssertionError: can only join a started process.
--> 719             w.start()
    720             self._index_queues.append(index_queue)
    721             self._workers.append(w)

d:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

d:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

d:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

d:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     63             try:
     64                 reduction.dump(prep_data, to_child)
---> 65                 reduction.dump(process_obj, to_child)
     66             finally:
     67                 set_spawning_popen(None)

d:\ProgramData\Anaconda3\envs\pytorch\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\multiprocessing\reductions.py in reduce_tensor(tensor)
    240          ref_counter_offset,
    241          event_handle,
--> 242          event_sync_required) = storage._share_cuda_()
    243         tensor_offset = tensor.storage_offset()
    244         shared_cache[handle] = StorageWeakRef(storage)

RuntimeError: cuda runtime error (801) : operation not supported at C:\w\1\s\windows\pytorch\torch/csrc/generic/StorageSharing.cpp:245

**Comment by sgugger** [comment]
See the [forum](https://forums.fast.ai/) for how to use fastai on Windows. In particular you always need to set `num_workers=0` when creating a `DataLoaders` because Pytorch multiprocessing does not work on Windows.

**Comment by SeriousHyena** [comment]
Thanks Sgugger, Setting num_workers=0 solved my problem. I appreciate it.

serioushyena

**Comment by Kantulaev** [comment]
me too! it work

**Comment by chandrasekar19102** [comment]
> See the [forum](https://forums.fast.ai/) for how to use fastai on Windows. In particular you always need to set `num_workers=0` when creating a `DataLoaders` because Pytorch multiprocessing does not work on Windows.



> me too! it work

I m also having this issue please kindly help me out

**Comment by Kantulaev** [comment]
> 
> 
> > See the [forum](https://forums.fast.ai/) for how to use fastai on Windows. In particular you always need to set `num_workers=0` when creating a `DataLoaders` because Pytorch multiprocessing does not work on Windows.
> 
> > me too! it work
> 
> I m also having this issue please kindly help me out

Just add num_workers = 0 in your dls (after all parameters )

**Comment by Lundez** [comment]
@Kantulaev got a clue how to fix `predict`, it's also crashing because of the same issue and has no `num_workers`  param..

**Comment by Kantulaev** [comment]
> @Kantulaev got a clue how to fix `predict`, it's also crashing because of the same issue and has no `num_workers`  param..

I just switched to linux mint

**Comment by SheaCodes** [comment]
> @Kantulaev got a clue how to fix `predict`, it's also crashing because of the same issue and has no `num_workers` param..

I also have this issue...

**Comment by Lundez** [comment]
> > @Kantulaev got a clue how to fix `predict`, it's also crashing because of the same issue and has no `num_workers` param..
> 
> I also have this issue...

Downgrade to 2.0.8 works fine 👍

**Comment by issactoast** [comment]
> > > @Kantulaev got a clue how to fix `predict`, it's also crashing because of the same issue and has no `num_workers` param..
> > 
> > 
> > I also have this issue...
> 
> Downgrade to 2.0.8 works fine 👍

downgrade to 2.0.8 still doesn't work for me. :/

**Comment by keplaxo** [comment]
Thanks, adding num_workers = 0 sorted it out.

**Comment by daelsh** [comment]
Hey guys,

I'm quite new to fastai.

I have the same problem on windows.

Where should I put "num_workers = 0"? 

What file should I edit?

Best regards
David

**Comment by Lundez** [comment]
In each dls creation (DataLoaders) 👍

Den tors 12 nov. 2020 11:19daelsh <notifications@github.com> skrev:
